### ISSUE TITLE
Legal Imprint to be updated

### ISSUE THREAD

**Issue by mschwit** [Daimler/daimler-foss#29]
Jonas von Malottki is not CEO of Daimler Protics GmbH anymoer but Kai Fischer ist. Please change https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md accordingly

**Comment by fafa0803** [comment]
Hello @mschwit,

thank you for informing us about that. The Legal_Imprint.md is an old file, which is still needed for older pull-requests, but is no longer updated. 
I updated the information in the [Provider_Information.md](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md). 

Fabian Faulhaber fabian.faulhaber@daimler.com, Daimler AG on behalf of Daimler TSS GmbH, [Imprint](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md).
